language: cpp

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libboost-all-dev
    - libboost-random-dev
    - gcc-4.8
    - g++-4.8
    - libarmadillo-dev
    - libgtest-dev

script:
  - qmake adamant-broccoli.pro
  - sed -i 's/= gcc/= gcc-4.8/g' Makefile
  - sed -i 's/= g++/= g++-4.8/g' Makefile
  - make
